### ISSUE TITLE
Server Configuration

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/MongoDB#17]
We could not change as not permission
https://docs.mongodb.com/manual/administration/production-notes/#recommended-configuration

This capability provides “data center awareness,” which allows applications to target MongoDB deployments with consideration of the physical location of the mongod instances. MongoDB supports segmentation of operations across different dimensions, which may include multiple data centers and geographical regions in multi-data center deployments, racks, networks, or power circuits in single data center deployments.

We don't know the details of how server is configurated
https://docs.mongodb.com/manual/core/operational-segregation/#operational-overview

**Comment by xpdavid** [comment]
https://docs.mongodb.com/manual/administration/configuration/#configure-the-database
```yaml
sharding:
  clusterRole: shardsvr
storage:
   dbPath: /srv/mongodb/db0/
   wiredTiger:
      engineConfig:
         cacheSizeGB: 16
processManagement:
   fork: true
   pidFilePath: /srv/mongodb/db0.pid
net:
   bindIp: 127.0.0.1
   port: 27017
systemLog:
   destination: file
   path: "/var/log/mongodb/mongod.log"
   logAppend: true
storage:
   journal:
      enabled: true
replication:
   replSetName: set0
```

```javascript
rs.initiate({
   _id : "set0",
   members: [ 
      { _id : 0, host : "mongodb0.example.net:27017" },
      { _id : 1, host : "mongodb1.example.net:27017" },
      { _id : 2, host : "mongodb2.example.net:27017" }
   ]
})
```

**Comment by xpdavid** [comment]
https://docs.mongodb.com/manual/administration/configuration/#sharding-configuration
```yaml
sharding:
    clusterRole: configsvr
 net:
    bindIp: 10.8.0.12
    port: 27001
replication:
    replSetName: csRS
```
```shell
rs.initiate(
  {
    _id: "csRS",
    configsvr: true,
    members: [
      { _id : 0, host : "cfg1.example.net:27019" },
      { _id : 1, host : "cfg2.example.net:27019" },
      { _id : 2, host : "cfg3.example.net:27019" }
    ]
  }
)
```
